### ISSUE TITLE
"delete a promotions" BDD feature

### ISSUE THREAD

**Issue by GaryAvc** [PromoSquad/promotions#112]
**As a** Developer
**I need** a feature describing deleting a promotion
**So that** I can test deleting a promotion under BDD

**Acceptance Criteria:**

```gherkin
When I run `behave`
Then I should see the scenario "delete a promotion" pass 
```

**Comment by rladuddlf** [comment]
Is this one same as #107 ?

**Comment by dizys** [comment]
IBM Cloud [toolchain](https://cloud.ibm.com/devops/toolchains/555adb64-8497-4119-b8ce-3e3c764c7597?env_id=ibm:yp:us-south "nyu-devops-promotions-toolchain"): [Delivery Pipeline](https://cloud.ibm.com/devops/pipelines/70ccc3da-a493-45e2-9db5-075c3d858058 "nyu-promotion-service-fall2103") deployed [promotions](https://github.com/PromoSquad/promotions/releases/tag/deploy-ibm-yp-us-south-yk2494-nyu.edu-prod-20211205-214310 "deploy-ibm-yp-us-south-yk2494-nyu.edu-prod-20211205-214310") to [prod](https://console.bluemix.net/apps/05bb5f7f-3579-466f-b3c0-177b78bf73e4?env_id=ibm:yp:us-south "ibm:yp:us-south:yk2494@nyu.edu:prod"), including commits 508a0066f84244899946d1747f7565fb0bfa0a0c, a6d4b7fe71931fe706458f06f3e1ad04f47a58c4
