### ISSUE TITLE
Implement test: list all promotions

### ISSUE THREAD

**Issue by dizys** [PromoSquad/promotions#28]
**As a** developer
**I need** test for "listing all promotions" API to function properly in test-driven development
**So that** then I can work on implementing promotion listing API

**Details & Assumptions:** 

* We should test the API that lists all promotions

**Acceptance Criteria:**

```gherkin
When I run `nosetests`
Then I should expect the tests to run, including this promotion listing test
```

**Comment by rladuddlf** [comment]
Seems like this issue along with #26 and #27 are being redundant with #22~#24. Should I delete mine? Let me know :)

**Comment by dizys** [comment]
It's actually different if you look close. This is for implementing test, and the other is for implementing API. Care for the difference, because we are developing our services in a test-driven approach, which means we should first implementing tests and then develop the actual API service to pass the test.

**Comment by rladuddlf** [comment]
Oh yeah that makes sense. Great.
