### ISSUE TITLE
Integrate Pull Requests notification with Slack Channel

### ISSUE THREAD

**Issue by dizys** [PromoSquad/promotions#59]
**As a** developer
**I need** real-time notification for a pull request on slack channel
**So that** I can handle them in time

**Details & Assumptions:** 

* Slack channel is our #promotions team channel

**Acceptance Criteria:**

```gherkin
When a new pull request is created
Then I should see a message about it being sent by bot in our channel
```

**Comment by Tingtingyy** [comment]
https://nyu-devops-fall2021-3.slack.com/apps/A01BP7R4KNY-github?tab=more_info
